name: Update keys

on:
  schedule:
    - cron: "57 * * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update keys
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: keys

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2

      - name: Setup NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get keys
        run: pnpm getkeys

      - name: Checkout keys branch
        uses: actions/checkout@v4
        with:
          ref: keys
          path: key_repo

      - name: Update key if it differs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add keys.json
          git commit --allow-empty -m "Update keys.json"
          git stash
          git pull --rebase
          git stash pop || true
          git add keys.json
          git commit --allow-empty -m "Update keys.json"
          git push
